services:
  flask:
    build: .
    image: lorax:latest
    environment:
      LORAX_RQ_REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:6.2.2-alpine3.13
    healthcheck:
      test: "redis-cli ping"

  rq_worker_alignment:
    image: lorax:latest
    command: rq worker --url redis://redis:6379 alignment
    depends_on:
      redis:
        condition: service_healthy
# in case "flask" image is rebuilt
      flask:
        condition: service_started

  rq_worker_treebuilding:
    image: lorax:latest
    command: rq worker --url redis://redis:6379 treebuilding
    depends_on:
      redis:
        condition: service_healthy
# in case "flask" image is rebuilt
      flask:
        condition: service_started

# https://github.com/Parallels/rq-dashboard#installing-with-docker
  rq_dashboard:
    image: eoranged/rq-dashboard:v0.6.3
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379
    ports:
      - "9181:9181"
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - rq_dashboard
