services:
  flask:
    environment:
      FLASK_APP: lorax
      FLASK_ENV: development
    restart: "no"
    volumes:
      - ./lorax:/usr/src/app/lorax:ro
    command: flask run --host=0.0.0.0 --port=8000

  load:
    volumes:
      - ./lorax:/usr/src/app/lorax:ro

  rq_worker_alignment:
    restart: "no"
    volumes:
      - ./lorax:/usr/src/app/lorax:ro

  rq_worker_treebuilding:
    restart: "no"
    volumes:
      - ./lorax:/usr/src/app/lorax:ro

  test:
    volumes:
      - ./lorax:/usr/src/app/lorax:ro
